// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARjvRvRVKFEOdr4KQw8ObDHRVoe9h6wbU',
    appId: '1:467512301114:web:15a7d2e63ec2717a680703',
    messagingSenderId: '467512301114',
    projectId: 'todo-asyn-app',
    authDomain: 'todo-asyn-app.firebaseapp.com',
    storageBucket: 'todo-asyn-app.firebasestorage.app',
    measurementId: 'G-JQXRD9KF7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_DkxgeRoXReMDGazZVXXH_uPYL7Xzfw',
    appId: '1:467512301114:android:03b2323447afe8ae680703',
    messagingSenderId: '467512301114',
    projectId: 'todo-asyn-app',
    storageBucket: 'todo-asyn-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0BBnRHPLK6rdZiU7EBmoZmeUxjt4oHvc',
    appId: '1:467512301114:ios:ccadb4beb7ae1be4680703',
    messagingSenderId: '467512301114',
    projectId: 'todo-asyn-app',
    storageBucket: 'todo-asyn-app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0BBnRHPLK6rdZiU7EBmoZmeUxjt4oHvc',
    appId: '1:467512301114:ios:ccadb4beb7ae1be4680703',
    messagingSenderId: '467512301114',
    projectId: 'todo-asyn-app',
    storageBucket: 'todo-asyn-app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARjvRvRVKFEOdr4KQw8ObDHRVoe9h6wbU',
    appId: '1:467512301114:web:bf29e96a9d2e02bb680703',
    messagingSenderId: '467512301114',
    projectId: 'todo-asyn-app',
    authDomain: 'todo-asyn-app.firebaseapp.com',
    storageBucket: 'todo-asyn-app.firebasestorage.app',
    measurementId: 'G-F8HVEJ23LY',
  );
}
